export const INIT_COUNTRIES = 'INIT_COUNTRIES';
export const CHOOSE_COUNTRY = 'CHOOSE_COUNTRY';
export const FETCH_PLACES = 'FETCH_PLACES';
export const UPDATE_SELECTED_PLACE = 'UPDATE_SELECTED_PLACE';
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';

